# This is a Terraform-managed file; manual changes will be overwritten.
# see https://github.com/workloads/github-organization/blob/main/templates/.terraform-docs.yml

---

# see https://terraform-docs.io/user-guide/configuration/formatter/
formatter: "markdown table"

# see https://terraform-docs.io/user-guide/configuration/output/
output:
  file: "README.md"
  mode: inject
  content: |-
    {{ .Header }}

    ## Example

    ```hcl
    {{ include "examples/main.tf" }}
    ```
    

    {{ .Inputs }}
    {{ .Outputs }} 

    

# see https://terraform-docs.io/user-guide/configuration/settings/
settings:
  anchor: false
  color: true
  default: true
  description: true
  escape: true
  indent: 3
  required: true
  sensitive: true
  type: true

# see https://terraform-docs.io/user-guide/configuration/sort/
sort:
  enabled: true
  by: required

# see https://terraform-docs.io/user-guide/configuration/sections/
sections:
  sections:
  hide:
    - header
    - footer

# see https://terraform-docs.io/user-guide/configuration/content/
content: |-
    {{ .Header }}

    ## Example

    ```hcl
    {{ include "examples/example1/main.tf" }}
    ```
    ```hcl
    {{ include "examples/example2/main.tf" }}
    ```
    

    {{ .Inputs }}
    {{ .Outputs }} 

# see https://terraform-docs.io/user-guide/configuration/version/
version: ">= 0.17.0, < 1.0.0"